### ISSUE TITLE
Any file to reproduce the Roberta result?

### ISSUE THREAD

**Issue by PosoSAgapo** [CogComp/MCTACO#11]
I noticed the script of reproducing Bert result, but there is a Roberta folder under the experiment folder. Any file to run a Roberta model ? I m interested in using different language models to see their temporal commensense reasoning ability. Since the package used in Bert is not huggingface transformers package, so it cannot be easily done by just changing the script's model specification parameters. Any future plans in updating the Roberta running script?

**Comment by Slash0BZ** [comment]
Hi, the code I included for BERT is Huggingface's package, it's just really old back when it was called a different name. Unfortunately, I don't have anything available now for Roberta, my suggestion is to use Huggingface's provided code for SNLI and replace the data files' content with MCTACO's instances. This would require virtually zero change to the code. Please let me know if it works, thank you.

**Comment by PosoSAgapo** [comment]
For what I have found, there is no official implementation of Huggingface in SNLI. Therefore, I modified your Bert code  and reimplemented it with Huggingface Roberta. Simple experiments with Roberta-base and Roberta-large gives the following result:

> Roberta-base EM 0.42 F1:0.69
>Roberta-large EM 0.48 F1:0.74

However, I removed some features that implemented in your Bert code, like Apex's acceleration support and Distributed Trainning  so that I don't waste too much time in modifying features that I do not need. 
Since it is based on you Bert code ,so your script running code could also perfectly work with this reimplemented Roberta code. If this helps in reproducing Roberta result, I can send a pull request which you can merge, since it is implemented in Huggingface, basically all transformer models could be tesed on MCTACO now.

**Comment by Slash0BZ** [comment]
Good to know, thank you. Feel free to send a PR anytime. 

Ben

**Comment by PosoSAgapo** [comment]
I have sent the PR, you can merge it now. 
Thank you for your reply.

**Comment by Slash0BZ** [comment]
Thank you. Closing this now and we can discuss it in the PR if nessccary.
