### ISSUE TITLE
About unit normalization

### ISSUE THREAD

**Issue by lzzhaha** [CogComp/MCTACO#13]
Hi,

Could you please **explicitly** explain how you perform unit normalization in the BERT baseline? I tried to understand the functions in the _time_normalization.py_ file but I coud not figure out how I should use them in the BERT baseline to reproduce the experiment. 

For instance, I don't know how you change the value accordinly after you normalize the unit. Moreover, how you handle the single forms and plural forms (e.g., hour vs hours) during unit normalization?

It would be great if you can **provide the code snipt** specifying how to do unit normalization in the BERT baseline as described in the paper.

Thank you very much!

**Comment by Slash0BZ** [comment]
I see the issue. You can do it easily from the code I provided under `script/`, it's just I forgot to include the main function. For each candidate answer, you run [the function here](https://github.com/CogComp/MCTACO/blob/master/scripts/time_normalization.py#L35) to find any potential quantity mentioned in the answer (e.g., "**several** years"), then, you check if there is a unit word mentioned in the answer (e.g., "minute", "minutes"), make sure you include both plural and singular here, but treat them as the same unit. As a final step, you can acquire the nearest unit by using the result from quantity extraction and the unit word (in plural form), e.g., "several years" will be "4.0 years", "a minute" will be "1.0 minutes (note the plural form)" to [this function](https://github.com/CogComp/MCTACO/blob/master/scripts/time_normalization.py#L63)

**Comment by lzzhaha** [comment]
Thanks.
But I found that such a implementation will give rise to the following bug:

Candidate answer:  
**"a billion weeks"**

Code:
```
s = "a billion weeks".split()
num = quantity(s[:-1])

unit = normalize_timex(" ".join([str(num), s[-1]]))

print("num: ", num)
print("unit: ", unit)
```

The output is as follows:

`num:  1000000000.0
unit:  centuries`

which is apparently wrong. 

Is it that I used the provided normalization functions in the wrong way or some other reasons?

**Comment by Slash0BZ** [comment]
"centuries" is the largest unit that we consider, so I would think the normalization is correct. Which unit do you think it should be?

**Comment by lzzhaha** [comment]
I agree that "centuries" is the closest unit. 
But the problem is the **quantity** remains the same regardless of the change of units, which causes the **change in the semantics** of the candidate answer (i.e., "a billion weeks" is not the same as "1000000000.0 centuries").
So I don't think such a transformation is correct.
Thanks.

**Comment by Slash0BZ** [comment]
Sure, but the normalization only considers normalizing to the closest unit. You can, however, get the numerical value by dividing the value in seconds ([here](https://github.com/CogComp/MCTACO/blob/master/scripts/time_normalization.py#L82)) with the value in seconds the normalized unit has.

**Comment by lzzhaha** [comment]
Got it. Thanks
