### ISSUE TITLE
data path

### ISSUE THREAD

**Issue by HeglerTissot** [CogComp/MCTACO#5]
Repo has a "./dataset" directory, but code actually looks for "./data". Copying files to the required path seems to work, but it would be nice to see it fixed.

**Comment by Slash0BZ** [comment]
See #6

**Comment by joecummings** [comment]
#6 appears to address this issue for the evaluator; however, the `data_dir` argument still incorrectly uses `data` instead of `dataset` in `experiments/bert/run_bert_baseline.sh`.
