### ISSUE TITLE
Evaluation results

### ISSUE THREAD

**Issue by HeglerTissot** [CogComp/MCTACO#7]
The evaluation results seem to be inconsistent with those available in the AI2 leaderborad, as in the later there is no approach with F1=0.687.

python ./evaluator/evaluator.py eval --test_file data/test_9442.tsv --prediction_file bert_output/eval_outputs.txt

Strict Acc.: 0.40540540540540543
Avg F1: 0.6871234115992813

**Comment by Slash0BZ** [comment]
Yeah, I didn't put this result onto the leaderboard. Instead, there is an enhanced version BERT+unit normalization.
