### ISSUE TITLE
time unit normalization

### ISSUE THREAD

**Issue by lis-kp** [CogComp/MCTACO#8]
hello, I have started working on the MCTACO dataset recently and I wonder if there is also the script for the time unit normalization mentioned in the paper for the BERT baseline. thanks.

**Comment by Slash0BZ** [comment]
Thanks for your interest. Please see https://github.com/CogComp/MCTACO/blob/master/scripts/time_normalization.py. Let me know if you have any issues with it.

**Comment by lis-kp** [comment]
thanks a lot! that was really helpful!
