### ISSUE TITLE
question about unit normalization reproducibility

### ISSUE THREAD

**Issue by vincentlux** [CogComp/MCTACO#9]
Hi,

Thank you so much for releasing the unit normalization script! Since the script is not complete I tried to reproduce with the following rule
1.  for candidate time, convert all num-words to number if possible using `quantity` function
2.  pass converted number and the unit to the `normalize_timex` function to get a normalized unit
3. drop the number, and just use the normalized unit as new candidate time

After this, I can only get a score of 
```
Strict Acc.: 0.3708708708708709
Avg F1: 0.6483931942082973
```
May I ask if I misunderstood some parts of the normalization strategy? I really appreciate your kind help!

**Comment by Slash0BZ** [comment]
Yes, you are doing it right, except I kept the numbers (after normalization and rounded to a nearest integer) in the data. This will give the model a finer granularity in distinguishing the temporal expressions

**Comment by vincentlux** [comment]
Got it, I reproduced successfully. Thank you so much for your help!
